set -g base-index 1
set -g renumber-windows on

bind-key -n C-q confirm-before -p "Kill this tmux session? (y/n)" kill-session

#Plugin List
set -g @plugin 'vaaleyard/tmux-dotbar'

#Plugin Manager
run '~/.tmux/plugins/tpm/tpm'

#Dotbar Plugin Configuration
set -g @tmux-dotbar-position 'top'
set -g @tmux-dotbar-right true
set-option -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1
