background_opacity 1
shell /bin/zsh

font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 12.0

# GitHub Dark for kitty
foreground #c9d1d9
background #0d1117
cursor #c9d1d9
cursor_text_color #0d1117
selection_foreground #c9d1d9
selection_background #1f6feb

# Black
color0  #0d1117
# Red
color1  #ff7b72
# Green
color2  #3fb950
# Cyan
color3  #76e3ea
# Blue
color4  #58a6ff
# Magenta
color5  #8957e5
# Light Pink
color6  #d2a8ff
# Grey
color7  #8b949e

# Dark Grey
color8  #484f58
# Red
color9  #ff7b72
# Green
color10 #3fb950
# Cyan
color11 #76e3ea
# Blue
color12 #58a6ff
# Magenta
color13 #8957e5
# Light Pink
color14 #d2a8ff
# White
color15 #c9d1d9
